/**
 * Модели телефонов по маркам.
 *
 * Сначала списки были только у пяти марок, а у остальных шаг «Модель»
 * оказывался пустым: человек с Huawei доходил до него и упирался в
 * ничто. Пустой шаг хуже отсутствующего — он обещает выбор, которого
 * нет, и выглядит поломкой.
 *
 * Списки неполные по существу: телефонов выпускают сотни в год.
 * Поэтому у каждой марки внизу «Другая модель», а рядом с ней —
 * поле названия, куда продавец напишет своё.
 */
export const PHONE_MODELS_BY_BRAND: Record<string, string[]> = {
  Apple: [
    'iPhone 17 Pro Max',
    'iPhone 17 Pro',
    'iPhone 17',
    'iPhone Air',
    'iPhone 16 Pro Max',
    'iPhone 16 Pro',
    'iPhone 16 Plus',
    'iPhone 16',
    'iPhone 16e',
    'iPhone 15 Pro Max',
    'iPhone 15 Pro',
    'iPhone 15 Plus',
    'iPhone 15',
    'iPhone 14 Pro Max',
    'iPhone 14 Pro',
    'iPhone 14 Plus',
    'iPhone 14',
    'iPhone 13 Pro Max',
    'iPhone 13 Pro',
    'iPhone 13',
    'iPhone 13 mini',
    'iPhone 12 Pro Max',
    'iPhone 12 Pro',
    'iPhone 12',
    'iPhone 12 mini',
    'iPhone 11 Pro Max',
    'iPhone 11 Pro',
    'iPhone 11',
    'iPhone XR',
    'iPhone XS',
    'iPhone X',
    'iPhone SE',
    'iPhone 8',
    'iPhone 7',
  ],
  Samsung: [
    'Galaxy S25 Ultra',
    'Galaxy S25+',
    'Galaxy S25',
    'Galaxy S24 Ultra',
    'Galaxy S24+',
    'Galaxy S24',
    'Galaxy S23 Ultra',
    'Galaxy S23',
    'Galaxy S22 Ultra',
    'Galaxy S22',
    'Galaxy S21',
    'Galaxy S20',
    'Galaxy Z Fold 6',
    'Galaxy Z Fold 5',
    'Galaxy Z Flip 6',
    'Galaxy Z Flip 5',
    'Galaxy A56',
    'Galaxy A55',
    'Galaxy A36',
    'Galaxy A35',
    'Galaxy A26',
    'Galaxy A25',
    'Galaxy A16',
    'Galaxy A15',
    'Galaxy A05',
    'Galaxy M55',
    'Galaxy M35',
    'Galaxy Note 20',
  ],
  Xiaomi: [
    'Xiaomi 15 Ultra',
    'Xiaomi 15',
    'Xiaomi 14 Ultra',
    'Xiaomi 14',
    'Xiaomi 13',
    'Xiaomi 12',
    'Redmi Note 14 Pro',
    'Redmi Note 14',
    'Redmi Note 13 Pro',
    'Redmi Note 13',
    'Redmi Note 12 Pro',
    'Redmi Note 12',
    'Redmi Note 11',
    'Redmi 14C',
    'Redmi 13C',
    'Redmi 12',
    'Redmi 10',
    'POCO X7 Pro',
    'POCO X7',
    'POCO X6',
    'POCO F6',
    'POCO F5',
    'POCO M6',
    'POCO M5',
  ],
  Honor: [
    'Magic 7 Pro',
    'Magic 6 Pro',
    'Magic 6',
    'Magic 5',
    'Honor 400',
    'Honor 200 Pro',
    'Honor 200',
    'Honor 90',
    'Honor 70',
    'Honor X9c',
    'Honor X9b',
    'Honor X9a',
    'Honor X8b',
    'Honor X8',
    'Honor X7',
    'Honor X6',
    'Honor 50',
  ],
  Huawei: [
    'Pura 70 Ultra',
    'Pura 70 Pro',
    'Pura 70',
    'P60 Pro',
    'P60',
    'P50 Pro',
    'P50',
    'P40 Pro',
    'P40 lite',
    'P30 Pro',
    'P30 lite',
    'Mate 60 Pro',
    'Mate 50 Pro',
    'Mate 40 Pro',
    'Mate X6',
    'Mate X5',
    'Nova 13',
    'Nova 12',
    'Nova 11',
    'Nova 10',
    'Nova 9',
    'Y9a',
    'Y8p',
    'Y6p',
  ],
  Realme: [
    'GT 7 Pro',
    'GT 6',
    'GT 5',
    'GT Neo 6',
    'GT Neo 5',
    'Realme 13 Pro+',
    'Realme 13 Pro',
    'Realme 12 Pro+',
    'Realme 12',
    'Realme 11 Pro',
    'Realme 11',
    'Realme 10',
    'Realme 9',
    'Realme C67',
    'Realme C55',
    'Realme C35',
    'Realme Note 60',
  ],
  Google: [
    'Pixel 10 Pro',
    'Pixel 10',
    'Pixel 9 Pro XL',
    'Pixel 9 Pro',
    'Pixel 9',
    'Pixel 8 Pro',
    'Pixel 8',
    'Pixel 8a',
    'Pixel 7 Pro',
    'Pixel 7',
    'Pixel 7a',
    'Pixel 6 Pro',
    'Pixel 6',
    'Pixel 6a',
    'Pixel 5',
    'Pixel 4a',
  ],
  OnePlus: [
    'OnePlus 13',
    'OnePlus 12',
    'OnePlus 12R',
    'OnePlus 11',
    'OnePlus 10 Pro',
    'OnePlus 10T',
    'OnePlus 9 Pro',
    'OnePlus 9',
    'OnePlus Nord 4',
    'OnePlus Nord 3',
    'OnePlus Nord CE 4',
    'OnePlus Nord CE 3',
    'OnePlus 8 Pro',
  ],
  Nothing: [
    'Phone (3)',
    'Phone (2a) Plus',
    'Phone (2a)',
    'Phone (2)',
    'Phone (1)',
    'CMF Phone 2 Pro',
    'CMF Phone 1',
  ],
  Motorola: [
    'Edge 50 Ultra',
    'Edge 50 Pro',
    'Edge 50 Fusion',
    'Edge 40 Neo',
    'Edge 40',
    'Edge 30',
    'Moto G85',
    'Moto G84',
    'Moto G54',
    'Moto G34',
    'Moto G24',
    'Moto G14',
    'Razr 50 Ultra',
    'Razr 40 Ultra',
    'Razr 40',
  ],
  Vivo: [
    'X200 Pro',
    'X200',
    'X100 Pro',
    'X100',
    'X90',
    'V40',
    'V30',
    'V29',
    'Y100',
    'Y58',
    'Y36',
    'Y27',
    'Y17s',
    'Y03',
  ],
  OPPO: [
    'Find X8 Pro',
    'Find X8',
    'Find X7 Ultra',
    'Find X6 Pro',
    'Find N5',
    'Find N3',
    'Reno 13 Pro',
    'Reno 12 Pro',
    'Reno 12',
    'Reno 11',
    'Reno 10',
    'Reno 8',
    'A79',
    'A78',
    'A58',
    'A38',
    'A18',
  ],
  Tecno: [
    'Phantom V Fold 2',
    'Phantom X2 Pro',
    'Camon 30 Pro',
    'Camon 30',
    'Camon 20 Pro',
    'Camon 20',
    'Spark 30 Pro',
    'Spark 30',
    'Spark 20 Pro',
    'Spark 20',
    'Pova 6 Pro',
    'Pova 5',
    'Pop 9',
    'Pop 8',
  ],
  Infinix: [
    'Note 40 Pro+',
    'Note 40 Pro',
    'Note 40',
    'Note 30 Pro',
    'Note 30',
    'Zero 40',
    'Zero 30',
    'Hot 50 Pro',
    'Hot 50',
    'Hot 40 Pro',
    'Hot 40',
    'Smart 9',
    'Smart 8',
  ],
  ZTE: [
    'nubia Z70 Ultra',
    'nubia Z60 Ultra',
    'nubia Flip 2',
    'nubia Neo 3',
    'Blade V60',
    'Blade V50',
    'Blade A75',
    'Blade A55',
    'Axon 50 Ultra',
    'Axon 40 Ultra',
  ],
  Nokia: [
    'G42',
    'G22',
    'G21',
    'G11',
    'C32',
    'C22',
    'C21',
    'XR21',
    'X30',
    'X20',
    '110 (кнопочный)',
    '105 (кнопочный)',
    '3310 (кнопочный)',
    '8210 (кнопочный)',
  ],
  Другая: ['Кнопочный телефон', 'Смартфон', 'Другое'],
};

/**
 * Сколько памяти бывает у модели.
 *
 * Расписано для тех, где ошибиться легко и обидно: «айфон на 32 ГБ»
 * не существует, и предлагать такой выбор нельзя. Для остальных марок
 * даём обычный ряд — он покрывает почти всё, что выпускалось.
 */
export const COMMON_STORAGE = ['32 ГБ', '64 ГБ', '128 ГБ', '256 ГБ', '512 ГБ', '1 ТБ'];
